######################
# LOCALHOST
######################

### OAuth
GET http://localhost:8080/

// ORDERS
### Get all orders
GET http://localhost:8080/orders

### Get order by id
GET http://localhost:8080/orders/6491c0350c550bf56ffbe5d3


// REVIEWS
### Get all reviews
GET http://localhost:8080/reviews

### Get review by ID
GET http://localhost:8080/reviews/649ba690bad05e5b5a1d54e3

### Create a review
POST http://localhost:8080/reviews HTTP/1.1
content-type: application/json

{
  "userEmail": "test@gmail.com",
  "productID": "2",
  "reviewText": "Testing, testing, testing, testing 123",
  "rating": "3",
  "date": "6/27/2023",
  "otherDetails": "Test details"
}

### Update a review
PUT http://localhost:8080/reviews/649ba57cbad05e5b5a1d54db HTTP/1.1
content-type: application/json

{
  "userEmail": "test1@gmail.com",
  "productID": "1",
  "reviewText": "updated Testing, testing, testing, testing 123",
  "rating": "4",
  "date": "6/26/2023",
  "otherDetails": "updated Test details"
}

### Delete a review
DELETE http://localhost:8080/reviews/649ba57cbad05e5b5a1d54db HTTP/1.1


// PRODUCTS
### GET all products
GET http://localhost:8080/products HTTP/1.1
### GET one product
GET http://localhost:8080/products/6494709ffef8b2872b3a1c2e HTTP/1.1
### CREATE a new product
POST http://localhost:8080/products HTTP/1.1
content-type: application/json

{
  "name": "Hersey Kisses",
  "description": "Small chocolate tear drop candies.",
  "price": "3.99",
  "quantityInStock": "55",
  "category": "Candy",
  "brand": "Hersey",
  "images": "kisses1234.png",
  "otherDetails": "store in a cool place"
}
### UPDATE a product
PUT http://localhost:8080/products/6494709ffef8b2872b3a1c2e HTTP/1.1
content-type: application/json

{
  "name": "Kisses",
  "description": "Small chocolate tear drop candies.",
  "price": "3.99",
  "quantityInStock": "55",
  "category": "Candy",
  "brand": "Hersey",
  "images": "kisses1234.png",
  "otherDetails": "It should be store in a cool place."
}
### DELETE a product
DELETE http://localhost:8080/products/649471e4fef8b2872b3a1c34 HTTP/1.1
